# Generated by Django 5.2.6 on 2025-09-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_assignee_task_board_task_comments_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
