# Generated by Django 5.2.6 on 2025-09-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_alter_task_due_date_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
