# Generated by Django 5.2.6 on 2025-09-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_remove_comment_created_at_remove_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
